name: Update Age in README

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate Age
        run: |
          BIRTH_YEAR=2002  # Replace with your birth year
          BIRTH_MONTH=8     # Replace with your birth month
          BIRTH_DAY=6      # Replace with your birth day
          TODAY=$(date +%Y-%m-%d)
          BIRTHDATE=$(date -d "$BIRTH_YEAR-$BIRTH_MONTH-$BIRTH_DAY" +%Y-%m-%d)
          AGE=$(( $(date -d "$TODAY" +%Y) - $(date -d "$BIRTHDATE" +%Y) ))
          
          if [[ "$(date -d "$TODAY" +%m%d)" -lt "$(date -d "$BIRTHDATE" +%m%d)" ]]; then
            AGE=$((AGE - 1))  # Adjust age if birthday hasn't occurred yet this year
          fi

          echo "AGE=$AGE" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/{{AGE}}/${AGE}/g" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated age in README.md" || exit 0
          git push
